import os, glob

hook_ids = [
    'Hook_hky_120_devil',
    'Hook_hky_13_hard',
    'Hook_hky_157_devil',
    'Hook_hky_160_devil',
    'Hook_hky_164_devil',
    'Hook_hky_209_devil',
    'Hook_hky_348_devil',
    'Hook_htl_100_easy',
    'Hook_htl_102_hard',
    'Hook_htl_105_normal',
    'Hook_htl_106_hard',
    'Hook_htl_109_easy',
    'Hook_htl_10_easy',
    'Hook_htl_112_easy',
    'Hook_htl_117_easy',
    'Hook_htl_118_devil',
    'Hook_htl_119_easy',
    'Hook_htl_122_hard',
    'Hook_htl_123_easy',
    'Hook_htl_127_hard',
    'Hook_htl_128_easy',
    'Hook_htl_135_easy',
    'Hook_htl_141_normal',
    'Hook_htl_144_easy',
    'Hook_htl_145_normal',
    'Hook_htl_147_devil',
    'Hook_htl_152_normal',
    'Hook_htl_154_normal',
    'Hook_htl_155_hard',
    'Hook_htl_161_easy',
    'Hook_htl_168_normal',
    'Hook_htl_175_devil', 
    'Hook_htl_175_hard', 
    'Hook_htl_178_devil',
    'Hook_htl_179_devil',
    'Hook_htl_181_normal',
    'Hook_htl_186_hard',
    'Hook_htl_189_hard',
    'Hook_htl_18_easy',
    'Hook_htl_194_hard',
    'Hook_htl_209_hard',
    'Hook_htl_20_hard',
    'Hook_htl_210_easy',
    'Hook_htl_217_hard',
    'Hook_htl_222_hard',
    'Hook_htl_224_devil',
    'Hook_htl_22_normal',
    'Hook_htl_232_hard',
    'Hook_htl_23_devil',
    'Hook_htl_240_normal',
    'Hook_htl_245_hard',
    'Hook_htl_251_devil',
    'Hook_htl_262_devil',
    'Hook_htl_264_normal',
    'Hook_htl_273_normal',
    'Hook_htl_284_normal',
    'Hook_htl_291_normal',
    'Hook_htl_296_normal',
    'Hook_htl_306_normal',
    'Hook_htl_337_hard',
    'Hook_htl_338_hard',
    'Hook_htl_339_devil',
    'Hook_htl_375_hard',
    'Hook_htl_389_devil',
    'Hook_htl_40_easy',
    'Hook_htl_46_normal',
    'Hook_htl_55_devil',
    'Hook_htl_57_normal',
    'Hook_htl_68_easy',
    'Hook_htl_6_hard',
    'Hook_htl_70_normal',
    'Hook_htl_7_normal',
    'Hook_htl_83_easy',
    'Hook_htl_91_hard',
    'Hook_htl_92_normal',
    'Hook_htl_96_easy',
    'Hook_htl_97_hard'
]

all_path = glob.glob('*/*.urdf')

for path in all_path:
    flag = False
    for hook_id in hook_ids:
        if hook_id in path:
            flag = True
            break
    if not flag:
        print(f'not in list: {path}')